name: Build and Push Docker Image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: string
      uses: ASzc/change-string-case-action@v2
      with:
        string: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.string.outputs.lowercase }}
        platforms: linux/amd64,linux/arm64

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
